version: '3.1'

volumes:
  nextcloud_data:
  nextcloud_config:
  db:

networks:
  nextcloud_net:

services:
  db:
    image: mariadb
    container_name: nextcloud_db
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    networks:
      - nextcloud_net
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nextcloud
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PWD}
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=${DB_PWD}

  app:
    build: .
    container_name: nextcloud_app_custom
    restart: always
    depends_on:
      - db
    networks:
      - nextcloud_net
    ports:
      - 8443:443
    volumes:
      - nextcloud_data:/srv/nextcloud/data
      - nextcloud_config:/var/www/html/config
      - ./certs:/etc/apache2/certs
    environment:
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=${DB_PWD}
      - MYSQL_HOST=db
      - NEXTCLOUD_ADMIN_USER=${NEXTCLOUD_ADMIN}
      - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_PWD}
      - NEXTCLOUD_TRUSTED_DOMAINS=${SERVER_IP}
      - NEXTCLOUD_DATA_DIR=${DATA_DIR}

